### ISSUE TITLE
White accents aren't white

### ISSUE THREAD

**Issue by blyxyas** [catppuccin/youtubemusic#12]
Currently the accent color "White" is set to `var(--ctp-text)`, that color is:

* Frappe: `#c6d0f5`
* Latte: `#4c4f69`
* Macchiato: `#cad3f5`
* Mocha: `#cdd6f4`

These colors aren't white, Latte's white is a dark blue. It is a little bit confusing for a user expecting white (`#FFFFFF`) to encounter a color that isn't white, more like a "Lavender" color. The pastel colors choosen are great, but still.

**Comment by kerichdev** [comment]
As for the name - it's confusing, that can be changed. But the choice of colors themselves is not up to me, unfortunately.

**Comment by kerichdev** [comment]
Fixed in f4f86fc
