### ISSUE TITLE
Extremely large icons

### ISSUE THREAD

**Issue by blyxyas** [catppuccin/youtubemusic#14]
When clicking your icon (right, upper hand) some icons and texts display (Your channel, Settings, Log out...). The icons are so big that they overlap each other and hide the text.

![image](https://user-images.githubusercontent.com/73757586/211072641-5113ffde-5095-4b52-8ace-229b68525ef8.png)

**Comment by rubyowo** [comment]
The problematic commit has already been reverted, so could you try updating again?

**Comment by blyxyas** [comment]
Closing this issue.
It was due to a code I manually put in to try things, not because of the default theming.
