### ISSUE TITLE
Doesn't work on th-ch

### ISSUE THREAD

**Issue by uynilo9** [catppuccin/youtubemusic#21]
I click the "import custom css file", but it doesn't work at all.
(th-ch v3.2.2)

**Comment by MikeVensel** [comment]
@uynilo9 I just came across this issue myself. The issue looks to be with trying to reference the style using `@import`. It should work if you go into the css file you want in this repo and copy its contents into a css file on your machine.

There doesn't look to be any feedback in the app when the css file is imported but you need to go to Navigation > Restart App after importing the file. 

Hope that helps you!

**Comment by uynilo9** [comment]
@MikeVensel It actually works. Thank you so much for help <3

**Comment by Traace** [comment]
No, I did that and it still does not work. No theme gets applied. Using th-ch on Mac
