### ISSUE TITLE
Theme doesn't affect in-app menu in youtube-music by th-ch

### ISSUE THREAD

**Issue by NeoAtCatbox** [catppuccin/youtubemusic#22]
Hello! I would like to report an issue.
Looks like this theme doesn't modify so called "in-app menu" which is a built-in plugin for youtube-music for yt-ch, in-app menu makes the app look more native, but looks like this theme doesn't modify its default dark colors
![image](https://github.com/catppuccin/youtubemusic/assets/153903819/1643c885-196f-4f00-ab3a-ef04f85bf354)
I hope support for in-app menu will be added in future versions of this theme.

I use youtube-music by yt-ch v3.2.2.0

**Comment by kerichdev** [comment]
the built in app menu was not expected to be covered by the theme, but i'll look into what i can do

**Comment by kerichdev** [comment]
okay thats put on hold for a while since i dont have windows :3 my apologies

**Comment by kerichdev** [comment]
@redsauce117 this css class looks interesting - could it be that the in-app menu classes are generated on the fly now?

in that case i dont think we could define it in the theme as it'd keep changing.

**Comment by redsauce117** [comment]
I forgot to clarify. The CSS requires that you have the "In app menu" plugin enabled. 🤦‍♂️ Otherwise it still renders the title bar in a native window style!

**Comment by kerichdev** [comment]
looked into this after some time and a few updates have passed - and the class names seemed to stay the same, so will be fixing this - thanks @redsauce117!
