### ISSUE TITLE
Theme doesn't affect small-sized window panel

### ISSUE THREAD

**Issue by Hanif012** [catppuccin/youtubemusic#24]
As you can see the play button and the dark color when resizing

https://github.com/catppuccin/youtubemusic/assets/86117958/fd17a6ac-73b1-41ff-91ca-5b757e1910a7

**Comment by kerichdev** [comment]
huh, so presumably that's the new playing menu - i haven't seen that one yet myself, ill try to get around to themeing it if i manage to catch it

**Comment by kerichdev** [comment]
fixed in 4d48039 :heart:
