### ISSUE TITLE
ytmdesktop instructions are outdated

### ISSUE THREAD

**Issue by RuiNtD** [catppuccin/youtubemusic#39]
The instructions for installing on ytmdesktop are outdated, since the Appearance settings ask for a CSS file and don't have an editor.
![youtube-music-desktop-app_A6jPXyJrUs](https://github.com/catppuccin/youtubemusic/assets/1149870/43f9681b-916b-4071-87a9-43cee3c22870)

**Comment by kerichdev** [comment]
sharp eye! thanks for opening the issue <3
