### ISSUE TITLE
Add the stylus theme to the userstyles repository

### ISSUE THREAD

**Issue by Shutruk** [catppuccin/youtubemusic#40]
Hi!
After installing the full [userstyles repository pack](https://github.com/catppuccin/userstyles), the yt music [stylus theme ](https://github.com/catppuccin/youtubemusic/raw/main/src/youtubemusic.user.css)is missing, it would be nice to add it for future installs.

Thanks a lot!

**Comment by kerichdev** [comment]
hi there! the theme has been excluded from the userstyles repository on purpose, if i recall correctly. although i dont remember the exact reason - i do feel like it's intended - ill get back if i find why exactly

**Comment by NeonGamerBot-QK** [comment]
> hi there! the theme has been excluded from the userstyles repository on purpose, if i recall correctly. although i dont remember the exact reason - i do feel like it's intended - ill get back if i find why exactly

most likely because this also themes the app.

**Comment by kerichdev** [comment]
closed as not planned basically since yeah, it themes other clients too and has to ship client-specific fixes
