### ISSUE TITLE
Scrollbar and youtube music logo do not appear

### ISSUE THREAD

**Issue by AmrAb06** [catppuccin/youtubemusic#41]
I applied the theme using stylus on brave, and for some reason the youtube music logo and the scroll bar disappear. 
![image](https://github.com/user-attachments/assets/21431322-b0a2-40c6-b8af-e24ab57fb91b)

**Comment by kerichdev** [comment]
hi! this is intended behaviour :3 although the logo may not be - which could be the result of outdated links - ill take a look

**Comment by AmrAb06** [comment]
Why would the intention be to make the scroll bar disappear?

**Comment by kerichdev** [comment]
repeated failed attempts to theme it - although i should probably make it a toggle
