### ISSUE TITLE
Button not styled properly

### ISSUE THREAD

**Issue by hotsno** [catppuccin/youtubemusic#5]
<img width="1346" alt="image" src="https://user-images.githubusercontent.com/71658949/204152567-e56171f1-7bf8-4267-9f0a-d18fa8915002.png">

The "More" button seems to have invisible text for me.

**Comment by rubyowo** [comment]
Yep this is a known bug, will fix soon

**Comment by hotsno** [comment]
<img width="447" alt="image" src="https://user-images.githubusercontent.com/71658949/204152693-c7832bd8-aebf-4b03-830c-4fccdb198c20.png">

No worries, it also happens here in case you didn't know/the fix won't affect this button as well.
